server:
  port: 8080

spring:
  application:
    name: lorecraft-api
  
  profiles:
    active: dev
  
# Database configuration removed - using mock data in memory
  
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

logging:
  level:
    com.lorecraft: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: lorecraft-jwt-secret-key-2025-very-long-secret-key
  expiration: 86400000 # 24 hours

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true